### ISSUE TITLE
Bug: Creep DoT not implemented correctly

### ISSUE THREAD

**Issue by BeafCultist** [gmuGADIG/FetchQuest#142]
The creep should deal damage as soon as the player enters it, and then again for each second they stand in it.
Currently, damage is dealt whenever the creep's timer runs out. This means (if the timing lines up right) the player can stand in it for up to a second before ever being hurt.

Possible implementation:
on the creep's `on_body_entered` signal, deal damage immediately, and reset the timer.

**Comment by Justin1L8** [comment]
This issue was originally about the collider's size being too small. After looking into it more and talking with Jonathan, we found that this wasn't the real cause of the issue.
