### ISSUE TITLE
Add HUD art

### ISSUE THREAD

**Issue by micycle8778** [gmuGADIG/FetchQuest#181]
The hud art is split up into several different sprites that should be resized as the player buys upgrades from the shop.

[Art Drive](https://drive.google.com/drive/folders/1uwspgPbHYUJF6yC-SNfbN724oxVlH6oc)

**Comment by Justin1L8** [comment]
The final stamina art was implemented, but the rest is still placeholders. Keeping this issue until the entire HUD has final art.
